// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addAddressExclusions/": {
            "post": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "address exclusions"
                ],
                "summary": "Adds new address exclusions for the current user",
                "parameters": [
                    {
                        "type": "file",
                        "description": "the CSV file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.addAddressExclusionsReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/addCluster/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Add Cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "separator of the CSV file",
                        "name": "separator",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "controls whether the first line should be skiped",
                        "name": "hasHeader",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "the CSV file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.addClusterReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/addPrivateAttribution/": {
            "post": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "attribution"
                ],
                "summary": "Create a new attribution which is only visible for the current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "separator of the CSV file",
                        "name": "separator",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "controls whether the first line should be skiped",
                        "name": "hasHeader",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "the CSV file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.addAttributionReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/addPublicAttribution/": {
            "post": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "attribution"
                ],
                "summary": "Create a new attribution which is visible to all users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "separator of the CSV file",
                        "name": "separator",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "controls whether the first line should be skiped",
                        "name": "hasHeader",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "the CSV file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "comma separated values",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/address/{hash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Query for address, transaction or block",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.searchResponse"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/addressExclusionOverview/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address exclusions"
                ],
                "summary": "Address exclusion overview",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.addressExclusionOverviewReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/addressExclusionStatus/{address_hash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address exclusions"
                ],
                "summary": "Get the exclusion status of an address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "address hash",
                        "name": "address_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.addressExclusionStatusReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/addressOutputRange/{address_hash}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get outputs of the given address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "address hash",
                        "name": "address_hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "output offset",
                        "name": "offset",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.handlerAddressOutputRange.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.searchResponse"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/adminDeleteIdentity/{identityUID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Delete an arbitrary identity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0x123",
                        "name": "identityUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.identityReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/attributionOverview/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attribution"
                ],
                "summary": "Get all attributions of the current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.attributionOverviewReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/blk/{hash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Query for address, transaction or block",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.searchResponse"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/blkRange/{block_hash}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get transactions of the given block",
                "parameters": [
                    {
                        "type": "string",
                        "description": "block hash",
                        "name": "block_hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "transaction offset",
                        "name": "offset",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.handlerBlockRange.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.searchResponse"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/clusterLookup/{addressHash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Get all clusters of the given address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Address hash",
                        "name": "addressHash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.clusterLookupReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/clusterOverview/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Get all custom clusters of the current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.clusterOverviewReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/clusterSummary/{addressHash}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Get all clusters of an address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Address hash",
                        "name": "addressHash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "comma separated values",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/createIdentity/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Create a new identity",
                "parameters": [
                    {
                        "description": "Identity details",
                        "name": "identity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.getCreateIdentityReply.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.identityReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deleteAddressExclusion/{addressHash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address exclusions"
                ],
                "summary": "Deletes an address exclusion of the current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0x123",
                        "name": "addressHash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.deleteAddressExclusionReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deleteAllAddressExclusions/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address exclusions"
                ],
                "summary": "Delete all address exclusions of the current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.deleteAddressExclusionReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deleteAllClusters/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Delete all clusters of the current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.deleteClusterReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deleteAllPrivateAttributions/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attribution"
                ],
                "summary": "Delete all attributions of the current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.deleteAttributionReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deleteCluster/{cluster_uid}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Delete Cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0x123",
                        "name": "cluster_uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.deleteClusterReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deleteHeuristic/": {
            "post": {
                "description": "Deletes either all heuristics of the current user or all heuristics of a transaction of the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heuristic"
                ],
                "summary": "Deletes either all heuristics or all heuristics of a transaction",
                "parameters": [
                    {
                        "description": "Heuristic deletion request. Set delete_all to true, only if ALL heuristic should be deleted.",
                        "name": "heuristic",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/heuristics.DeleteHeuristicRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.deleteHeuristicReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deleteIdentity/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Delete the identity of the current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.identityReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deletePrivateAttribution/{attribution_uid}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attribution"
                ],
                "summary": "Delete an attribution belonging to the current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0x123",
                        "name": "attribution_uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.deleteAttributionReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deletePublicAttribution/{attribution_uid}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attribution"
                ],
                "summary": "Delete a public attribution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0x123",
                        "name": "attribution_uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.deleteAttributionReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/executeHeuristics/{hash}": {
            "post": {
                "description": "This call queues the given heuristics for the given transaction. Does not wait until the heuristic execution is finished.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heuristic"
                ],
                "summary": "Queues the execution of heuristics for the given transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0x123",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Heuristics to queue",
                        "name": "heuristic",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.getHeuristicExecutionReply.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.heuristicExecutionReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/getIdentities/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Get all identities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.identitiesReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/heuristicDescriptors/": {
            "get": {
                "description": "Returns available heuristic descriptors, which define the heuristic interface",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heuristic"
                ],
                "summary": "Gets available heuristic descriptors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.heuristicDescriptorReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/heuristicDetails/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heuristic"
                ],
                "summary": "Get the details of a heuristic",
                "parameters": [
                    {
                        "description": "Heuristic UID",
                        "name": "heuristic",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.handlerHeuristicsDetails.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/heuristics.FrontendHeuristicShort"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/heuristicList/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heuristic"
                ],
                "summary": "Lists all heuristics of the current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.heuristicListReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/heuristicStatus/{hash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heuristic"
                ],
                "summary": "Get the status of all heuristics per transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0x123",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.heuristicReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/heuristics/{hash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heuristic"
                ],
                "summary": "Get all heuristic defined for a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0x123",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.heuristicReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/heuristicsSummary/{heuristic_UID}": {
            "get": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "heuristic"
                ],
                "summary": "Heuristic Summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0x123",
                        "name": "heuristic_UID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "comma separated values",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/hmiLookup/{hash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Get HMI clusters per transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0x123",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.hmiLookupReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/meta/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "Get the status of all backend modules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.metaStatus"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mixingActivity/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Mixing Activity of an address",
                "parameters": [
                    {
                        "description": "Mixing activity request details",
                        "name": "activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.getMixingActivity.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.mixingActivityReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/modifyIdentity/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Modify an arbitrary identity",
                "parameters": [
                    {
                        "description": "Identity modification details",
                        "name": "identity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.getModifyIdentityReply.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.identityReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reverseLookup/{txhash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Connection lookup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction hash",
                        "name": "txhash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "search direction",
                        "name": "forward",
                        "in": "query"
                    },
                    {
                        "maximum": 90,
                        "type": "integer",
                        "description": "number of days to look back",
                        "name": "t",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.connectionLookupReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/search/{query}": {
            "get": {
                "description": "Search for blocks, addresses and transactions. Supports searching by hash or block ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Search for blocks, addresses and transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hash",
                        "name": "query",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.searchResponse"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/searchAttributions/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attribution"
                ],
                "summary": "Search all public attributions and the attributions belonging to the current user",
                "parameters": [
                    {
                        "description": "Search query",
                        "name": "attribution",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.getAttributionSearchReply.request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.attributionOverviewReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/shortestTransactionPath/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Get the shortest path between two transactions",
                "parameters": [
                    {
                        "description": "transactions between which the path should be found",
                        "name": "transactions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/heuristics.ShortestTransactionPathRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.shortestTransactionPathReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/spendingFingerprint/{hash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Get the spending fingerprint of a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "transaction hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.spendingFingerprintReply"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tx/{hash}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Query for address, transaction or block",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.searchResponse"
                        }
                    },
                    "500": {
                        "description": "encoding error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "analytics.MixingActivity": {
            "type": "object",
            "properties": {
                "block": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "ts": {
                                "type": "string"
                            }
                        }
                    }
                },
                "input_txs": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "txhash": {
                                "type": "string"
                            }
                        }
                    }
                },
                "privacytype": {
                    "type": "integer"
                },
                "txhash": {
                    "type": "string"
                }
            }
        },
        "attribution.FrontendAttribution": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "source": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "ts": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "client.AuthenticatorAssuranceLevel": {
            "type": "string",
            "enum": [
                "aal0",
                "aal1",
                "aal2",
                "aal3"
            ],
            "x-enum-varnames": [
                "AUTHENTICATORASSURANCELEVEL_AAL0",
                "AUTHENTICATORASSURANCELEVEL_AAL1",
                "AUTHENTICATORASSURANCELEVEL_AAL2",
                "AUTHENTICATORASSURANCELEVEL_AAL3"
            ]
        },
        "client.Identity": {
            "type": "object",
            "properties": {
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "description": "CreatedAt is a helper struct field for gobuffalo.pop.",
                    "type": "string"
                },
                "credentials": {
                    "description": "Credentials represents all credentials that can be used for authenticating this identity.",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/client.IdentityCredentials"
                    }
                },
                "id": {
                    "description": "ID is the identity's unique identifier.  The Identity ID can not be changed and can not be chosen. This ensures future compatibility and optimization for distributed stores such as CockroachDB.",
                    "type": "string"
                },
                "metadata_admin": {
                    "description": "NullJSONRawMessage represents a json.RawMessage that works well with JSON, SQL, and Swagger and is NULLable-"
                },
                "metadata_public": {
                    "description": "NullJSONRawMessage represents a json.RawMessage that works well with JSON, SQL, and Swagger and is NULLable-"
                },
                "recovery_addresses": {
                    "description": "RecoveryAddresses contains all the addresses that can be used to recover an identity.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.RecoveryIdentityAddress"
                    }
                },
                "schema_id": {
                    "description": "SchemaID is the ID of the JSON Schema to be used for validating the identity's traits.",
                    "type": "string"
                },
                "schema_url": {
                    "description": "SchemaURL is the URL of the endpoint where the identity's traits schema can be fetched from.  format: url",
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/client.IdentityState"
                },
                "state_changed_at": {
                    "type": "string"
                },
                "traits": {
                    "description": "Traits represent an identity's traits. The identity is able to create, modify, and delete traits in a self-service manner. The input will always be validated against the JSON Schema defined in ` + "`" + `schema_url` + "`" + `."
                },
                "updated_at": {
                    "description": "UpdatedAt is a helper struct field for gobuffalo.pop.",
                    "type": "string"
                },
                "verifiable_addresses": {
                    "description": "VerifiableAddresses contains all the addresses that can be verified by the user.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.VerifiableIdentityAddress"
                    }
                }
            }
        },
        "client.IdentityCredentials": {
            "type": "object",
            "properties": {
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": true
                },
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "description": "CreatedAt is a helper struct field for gobuffalo.pop.",
                    "type": "string"
                },
                "identifiers": {
                    "description": "Identifiers represents a list of unique identifiers this credential type matches.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "$ref": "#/definitions/client.IdentityCredentialsType"
                },
                "updated_at": {
                    "description": "UpdatedAt is a helper struct field for gobuffalo.pop.",
                    "type": "string"
                },
                "version": {
                    "description": "Version refers to the version of the credential. Useful when changing the config schema.",
                    "type": "integer"
                }
            }
        },
        "client.IdentityCredentialsType": {
            "type": "string",
            "enum": [
                "password",
                "totp",
                "oidc",
                "webauthn",
                "lookup_secret"
            ],
            "x-enum-varnames": [
                "IDENTITYCREDENTIALSTYPE_PASSWORD",
                "IDENTITYCREDENTIALSTYPE_TOTP",
                "IDENTITYCREDENTIALSTYPE_OIDC",
                "IDENTITYCREDENTIALSTYPE_WEBAUTHN",
                "IDENTITYCREDENTIALSTYPE_LOOKUP_SECRET"
            ]
        },
        "client.IdentityState": {
            "type": "string",
            "enum": [
                "active",
                "inactive"
            ],
            "x-enum-varnames": [
                "IDENTITYSTATE_ACTIVE",
                "IDENTITYSTATE_INACTIVE"
            ]
        },
        "client.RecoveryIdentityAddress": {
            "type": "object",
            "properties": {
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "description": "CreatedAt is a helper struct field for gobuffalo.pop.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt is a helper struct field for gobuffalo.pop.",
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "via": {
                    "type": "string"
                }
            }
        },
        "client.Session": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "Active state. If false the session is no longer active.",
                    "type": "boolean"
                },
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": true
                },
                "authenticated_at": {
                    "description": "The Session Authentication Timestamp  When this session was authenticated at. If multi-factor authentication was used this is the time when the last factor was authenticated (e.g. the TOTP code challenge was completed).",
                    "type": "string"
                },
                "authentication_methods": {
                    "description": "A list of authenticators which were used to authenticate the session.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.SessionAuthenticationMethod"
                    }
                },
                "authenticator_assurance_level": {
                    "$ref": "#/definitions/client.AuthenticatorAssuranceLevel"
                },
                "devices": {
                    "description": "Devices has history of all endpoints where the session was used",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.SessionDevice"
                    }
                },
                "expires_at": {
                    "description": "The Session Expiry  When this session expires at.",
                    "type": "string"
                },
                "id": {
                    "description": "Session ID",
                    "type": "string"
                },
                "identity": {
                    "$ref": "#/definitions/client.Identity"
                },
                "issued_at": {
                    "description": "The Session Issuance Timestamp  When this session was issued at. Usually equal or close to ` + "`" + `authenticated_at` + "`" + `.",
                    "type": "string"
                }
            }
        },
        "client.SessionAuthenticationMethod": {
            "type": "object",
            "properties": {
                "aal": {
                    "$ref": "#/definitions/client.AuthenticatorAssuranceLevel"
                },
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": true
                },
                "completed_at": {
                    "description": "When the authentication challenge was completed.",
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "provider": {
                    "description": "OIDC or SAML provider id used for authentication",
                    "type": "string"
                }
            }
        },
        "client.SessionDevice": {
            "type": "object",
            "properties": {
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "description": "Device record ID",
                    "type": "string"
                },
                "ip_address": {
                    "description": "IPAddress of the client",
                    "type": "string"
                },
                "location": {
                    "description": "Geo Location corresponding to the IP Address",
                    "type": "string"
                },
                "user_agent": {
                    "description": "UserAgent of the client",
                    "type": "string"
                }
            }
        },
        "client.VerifiableIdentityAddress": {
            "type": "object",
            "properties": {
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "description": "When this entry was created",
                    "type": "string"
                },
                "id": {
                    "description": "The ID",
                    "type": "string"
                },
                "status": {
                    "description": "VerifiableAddressStatus must not exceed 16 characters as that is the limitation in the SQL Schema",
                    "type": "string"
                },
                "updated_at": {
                    "description": "When this entry was last updated",
                    "type": "string"
                },
                "value": {
                    "description": "The address value  example foo@user.com",
                    "type": "string"
                },
                "verified": {
                    "description": "Indicates if the address has already been verified",
                    "type": "boolean"
                },
                "verified_at": {
                    "type": "string"
                },
                "via": {
                    "description": "VerifiableAddressType must not exceed 16 characters as that is the limitation in the SQL Schema",
                    "type": "string"
                }
            }
        },
        "clustering.Attribution": {
            "type": "object",
            "properties": {
                "isPublic": {
                    "type": "boolean"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "clustering.ClusterType": {
            "type": "string",
            "enum": [
                "hmi",
                "fmi",
                "custom"
            ],
            "x-enum-varnames": [
                "TypeHMI",
                "TypeFMI",
                "TypeCustom"
            ]
        },
        "clustering.FrontendAddress": {
            "type": "object",
            "properties": {
                "addresshash": {
                    "type": "string"
                },
                "output_count": {
                    "type": "integer"
                },
                "spent_output_count": {
                    "type": "integer"
                }
            }
        },
        "clustering.FrontendCluster": {
            "type": "object",
            "properties": {
                "addressCount": {
                    "type": "integer"
                },
                "addresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/clustering.FrontendAddress"
                    }
                },
                "attributions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/clustering.Attribution"
                    }
                },
                "bhash": {
                    "type": "string"
                },
                "bid": {
                    "type": "integer"
                },
                "ts": {
                    "type": "string"
                },
                "txhash": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/clustering.ClusterType"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "clustering.FrontendHMICluster": {
            "type": "object",
            "properties": {
                "addressCount": {
                    "type": "integer"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "parent": {
                    "type": "string"
                },
                "txhash": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "clustering.FrontendUserCluster": {
            "type": "object",
            "properties": {
                "address_count": {
                    "type": "integer"
                },
                "addresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ts": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "db.FrontendTransaction": {
            "type": "object",
            "properties": {
                "bhash": {
                    "type": "string"
                },
                "bid": {
                    "type": "integer"
                },
                "bts": {
                    "type": "string"
                },
                "fee": {
                    "type": "integer"
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.FrontendTransactionOutput"
                    }
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.FrontendTransactionOutput"
                    }
                },
                "privacytype": {
                    "type": "integer"
                },
                "txhash": {
                    "type": "string"
                }
            }
        },
        "db.FrontendTransactionOutput": {
            "type": "object",
            "properties": {
                "addresshash": {
                    "type": "string"
                },
                "amount": {
                    "type": "integer"
                },
                "inputindex": {
                    "type": "integer"
                },
                "iscoinbase": {
                    "type": "boolean"
                },
                "keyasm": {
                    "type": "string"
                },
                "outputindex": {
                    "type": "integer"
                },
                "privacytype": {
                    "description": "This is data from either the transaction where this output is generated or spent",
                    "type": "integer"
                },
                "sigasm": {
                    "type": "string"
                },
                "ts": {
                    "type": "string"
                },
                "txhash": {
                    "type": "string"
                }
            }
        },
        "heuristics.Attribution": {
            "type": "object",
            "properties": {
                "isPublic": {
                    "type": "boolean"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "heuristics.DeleteHeuristicRequest": {
            "type": "object",
            "properties": {
                "delete_all": {
                    "type": "boolean"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "heuristics.Descriptor": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "parameter": {
                    "description": "pointer so Parameter does not appear in JSON if not set",
                    "type": "object",
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "type": {
                            "description": "Type must be one of the following values: 'int', 'string'",
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "heuristics.FrontendHeuristicCluster": {
            "type": "object",
            "properties": {
                "attributions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.Attribution"
                    }
                },
                "txs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.FrontendTransactionResult"
                    }
                }
            }
        },
        "heuristics.FrontendHeuristicResult": {
            "type": "object",
            "properties": {
                "destinations": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "ts": {
                                "type": "string"
                            },
                            "txhash": {
                                "type": "string"
                            },
                            "uid": {
                                "type": "string"
                            }
                        }
                    }
                },
                "origin": {
                    "type": "object",
                    "properties": {
                        "addresshash": {
                            "type": "string"
                        },
                        "ts": {
                            "type": "string"
                        },
                        "txhash": {
                            "type": "string"
                        },
                        "uid": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "heuristics.FrontendHeuristicShort": {
            "type": "object",
            "properties": {
                "clusters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.FrontendHeuristicCluster"
                    }
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "heuristics.FrontendTransactionResult": {
            "type": "object",
            "properties": {
                "destinationCount": {
                    "type": "integer"
                },
                "ts": {
                    "type": "string"
                },
                "txhash": {
                    "type": "string"
                }
            }
        },
        "heuristics.HeuristicListItem": {
            "type": "object",
            "properties": {
                "h_count": {
                    "type": "integer"
                },
                "mod_time": {
                    "type": "string"
                },
                "txhash": {
                    "type": "string"
                }
            }
        },
        "heuristics.HeuristicQueueStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "StatusHeuristicAdded",
                "StatusHeuristicDuplicate",
                "StatusHeuristicNotInQueue",
                "StatusHeuristicInQueue",
                "StatusHeuristicProcessing",
                "StatusHeuristicWorkerNotReady"
            ]
        },
        "heuristics.HollowHeuristic": {
            "type": "object",
            "properties": {
                "uid": {
                    "type": "string"
                }
            }
        },
        "heuristics.ShortestTransactionPathRequest": {
            "type": "object",
            "properties": {
                "anyDirection": {
                    "description": "AnyDirection determines the search direction of the shortest transaction path query\nTrue: Both inputs and outputs are traversed\nFalse: Only inputs are traversed",
                    "type": "boolean"
                },
                "from": {
                    "description": "From is the starting point of the shortest path lookup",
                    "type": "string"
                },
                "includePrivacyTransactions": {
                    "description": "IncludePrivacyTransactions determines if privacy transactions\nshould be considered when doing the shortest path lookup",
                    "type": "boolean"
                },
                "to": {
                    "description": "To is the end point of the shortest path lookup",
                    "type": "string"
                }
            }
        },
        "heuristics.TransformedFrontendHeuristic": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.HollowHeuristic"
                    }
                },
                "clusterCount": {
                    "type": "integer"
                },
                "clusterTypes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "excludeAddresses": {
                    "type": "boolean"
                },
                "excludeSpendingGaps": {
                    "type": "boolean"
                },
                "parameter": {
                    "type": "string"
                },
                "parent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.HollowHeuristic"
                    }
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.FrontendHeuristicResult"
                    }
                },
                "ts": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "heuristics.TransformedFrontendHeuristicRequest": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.HollowHeuristic"
                    }
                },
                "clusterTypes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/clustering.ClusterType"
                    }
                },
                "excludeSpendingGaps": {
                    "type": "boolean"
                },
                "parameter": {
                    "type": "string"
                },
                "parent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.HollowHeuristic"
                    }
                },
                "type": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "useAddressExclusionList": {
                    "type": "boolean"
                }
            }
        },
        "server.addAddressExclusionsReply": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.addAttributionReply": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.addClusterReply": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.addressExclusionOverviewReply": {
            "type": "object",
            "properties": {
                "addressCount": {
                    "type": "integer"
                },
                "addresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.addressExclusionStatusReply": {
            "type": "object",
            "properties": {
                "isExclusion": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.attributionOverviewReply": {
            "type": "object",
            "properties": {
                "attributions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/attribution.FrontendAttribution"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.clusterLookupReply": {
            "type": "object",
            "properties": {
                "clusters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/clustering.FrontendCluster"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.clusterOverviewReply": {
            "type": "object",
            "properties": {
                "clusters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/clustering.FrontendUserCluster"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.connectionLookupReply": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.FrontendTransaction"
                    }
                },
                "warning": {
                    "type": "boolean"
                }
            }
        },
        "server.deleteAddressExclusionReply": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.deleteAttributionReply": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.deleteClusterReply": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.deleteHeuristicReply": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.fingerprintScore": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "number"
                },
                "session_count": {
                    "type": "integer"
                },
                "txhash": {
                    "type": "string"
                }
            }
        },
        "server.getAttributionSearchReply.request": {
            "type": "object",
            "properties": {
                "q": {
                    "type": "string"
                }
            }
        },
        "server.getCreateIdentityReply.request": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "server.getHeuristicExecutionReply.request": {
            "type": "object",
            "properties": {
                "changed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.TransformedFrontendHeuristicRequest"
                    }
                },
                "deleted": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "server.getMixingActivity.request": {
            "type": "object",
            "properties": {
                "addressHash": {
                    "description": "AddressHash is the address hash for which the lookup will be done",
                    "type": "string"
                },
                "isClusterLookup": {
                    "description": "IsClusterLookup determines if all addresses of the cluster will be considered",
                    "type": "boolean"
                }
            }
        },
        "server.getModifyIdentityReply.request": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.FrontendRole"
                    }
                },
                "state": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "server.handlerAddressOutputRange.request": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "offset": {
                    "type": "integer"
                },
                "order": {
                    "type": "integer"
                }
            }
        },
        "server.handlerBlockRange.request": {
            "type": "object",
            "properties": {
                "offset": {
                    "type": "integer"
                }
            }
        },
        "server.handlerHeuristicsDetails.request": {
            "type": "object",
            "properties": {
                "uid": {
                    "type": "string"
                }
            }
        },
        "server.heuristicDescriptorReply": {
            "type": "object",
            "properties": {
                "descriptors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.Descriptor"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.heuristicExecutionReply": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/heuristics.HeuristicQueueStatus"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.heuristicListReply": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.HeuristicListItem"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.heuristicReply": {
            "type": "object",
            "properties": {
                "heuristics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/heuristics.TransformedFrontendHeuristic"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/heuristics.HeuristicQueueStatus"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.hmiLookupReply": {
            "type": "object",
            "properties": {
                "address_cluster": {
                    "type": "string"
                },
                "clusters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/clustering.FrontendHMICluster"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.identitiesReply": {
            "type": "object",
            "properties": {
                "identities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.Identity"
                    }
                },
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.Session"
                    }
                },
                "success": {
                    "type": "boolean"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.FrontendUserBackendState"
                    }
                }
            }
        },
        "server.identityReply": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.metaStatus": {
            "type": "object",
            "properties": {
                "rpcinfo": {
                    "$ref": "#/definitions/server.prunedRPCInfo"
                },
                "status": {
                    "$ref": "#/definitions/status.FrontendStatus"
                }
            }
        },
        "server.mixingActivityReply": {
            "type": "object",
            "properties": {
                "activities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.MixingActivity"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "server.prunedRPCInfo": {
            "type": "object",
            "properties": {
                "blocks": {
                    "type": "integer"
                },
                "difficulty": {
                    "type": "number"
                },
                "pruned": {
                    "type": "boolean"
                },
                "size_on_disk": {
                    "type": "integer"
                },
                "verificationprogress": {
                    "type": "number"
                }
            }
        },
        "server.queryResultType": {
            "type": "string",
            "enum": [
                "block",
                "addr",
                "tx",
                "response_empty"
            ],
            "x-enum-varnames": [
                "typeBlock",
                "typeAddr",
                "typeTx",
                "typeEmpty"
            ]
        },
        "server.searchResponse": {
            "type": "object",
            "properties": {
                "payload": {},
                "type": {
                    "$ref": "#/definitions/server.queryResultType"
                }
            }
        },
        "server.shortestTransactionPathReply": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.FrontendTransaction"
                    }
                }
            }
        },
        "server.spendingFingerprintReply": {
            "type": "object",
            "properties": {
                "fingerprint_scores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.fingerprintScore"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "session_count": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                },
                "warning": {
                    "type": "boolean"
                }
            }
        },
        "status.FrontendStatus": {
            "type": "object",
            "properties": {
                "isclassifying": {
                    "type": "boolean"
                },
                "isclusteringfmi": {
                    "type": "boolean"
                },
                "isclusteringhmi": {
                    "type": "boolean"
                },
                "iscrawling": {
                    "type": "boolean"
                },
                "lastblockid": {
                    "type": "integer"
                },
                "lastclassifiedid": {
                    "type": "integer"
                },
                "lastclusteredfmiid": {
                    "type": "integer"
                },
                "lastclusteredhmiid": {
                    "type": "integer"
                }
            }
        },
        "user.FrontendRole": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "user.FrontendUserBackendState": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "kratosID": {
                    "type": "string"
                },
                "modified": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.FrontendRole"
                    }
                },
                "uid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Dakar API",
	Description:      "This is the REST API for Dakar",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
