version: "3.6"
services:

  zero:
    image: dgraph/dgraph:latest
    container_name: zero
    volumes:
      - ${DGRAPH_PATH}:/dgraph
    ports:
      - ${CONTAINER_IP}:5080:5080
      - ${CONTAINER_IP}:6080:6080
    restart: ${RESTART_POLICY}
    command: dgraph zero --my=zero:5080 --enable_sentry=false
    networks:
      - dgraph_default

  alpha:
    image: dgraph/dgraph:latest
    container_name: alpha
    volumes:
      - ${DGRAPH_PATH}:/dgraph
    ports:
      - ${CONTAINER_IP}:8080:8080
      - ${CONTAINER_IP}:9080:9080
    expose:
      - 9080
    restart: ${RESTART_POLICY}
    command: dgraph alpha --my=alpha:7080 --lru_mb=${MEMORY_LIMIT} --zero=zero:5080 --whitelist 172.17.0.0:172.25.0.255,192.168.188.0:192.168.188.255 --query_edge_limit 10000000 --enable_sentry=false
    networks:
      - dgraph_default

  ratel:
    image: dgraph/dgraph:latest
    container_name: ratel
    ports:
      - ${CONTAINER_IP}:8000:8000
    expose:
      - 8000
    command: dgraph-ratel
    networks:
      - dgraph_default

  dakar_dashd:
    image: dashpay/dashd:latest
    container_name: dakar_dashd
    volumes:
      - ${DASH_PATH}:/dash
    ports:
      - ${CONTAINER_IP}:9999:9999
      - ${CONTAINER_IP}:9998:9998
    expose:
      - 9999
      - 9998
    restart: ${RESTART_POLICY}
    networks:
      - dgraph_default

networks:
  dgraph_default:
    external: true