version: "3.6"
services:

  zero:
    image: dgraph/dgraph:v21.03.2
    container_name: zero
    volumes:
      - ${DGRAPH_PATH}:/dgraph
    ports:
      - ${CONTAINER_IP}:5080:5080
      - ${CONTAINER_IP}:6080:6080
    restart: ${RESTART_POLICY}
    command: dgraph zero --my=zero:5080 --telemetry "reports=false; sentry=false"
    networks:
      - dgraph_default

  alpha:
    image: dgraph/dgraph:v21.03.2
    container_name: alpha
    volumes:
      - ${DGRAPH_PATH}:/dgraph
    ports:
      - ${CONTAINER_IP}:8080:8080
      - ${CONTAINER_IP}:9080:9080
    expose:
      - 9080
    restart: ${RESTART_POLICY}
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security "whitelist=192.168.188.0:192.168.188.255,172.16.0.0:172.31.255.255" --limit "query-edge=10000000" --telemetry "reports=false; sentry=false"
    networks:
      - dgraph_default

  ratel:
    image: dgraph/ratel:latest
    container_name: ratel
    ports:
      - ${CONTAINER_IP}:8000:8000
    expose:
      - 8000
    command: dgraph-ratel

  dashd:
    image: dashpay/dashd:18.0
    container_name: dashd
    volumes:
      - ${DASH_PATH}:/dash
    ports:
      - ${CONTAINER_IP}:9999:9999
      - ${CONTAINER_IP}:9998:9998
    expose:
      - 9999
      - 9998
    command: dashd
    restart: ${RESTART_POLICY}

#  bitcoind:
#    image: ruimarinho/bitcoin-core:23.0-alpine
#    container_name: bitcoind
#    volumes:
#      - ${BITCOIN_PATH}:/home/bitcoin/.bitcoin
#    ports:
#      - ${CONTAINER_IP}:8332:8332
#      - ${CONTAINER_IP}:8333:8333
#    expose:
#      - 8332
#      - 8333
#    restart: ${RESTART_POLICY}

networks:
  dgraph_default:
    external: true
