version: '3.6'

services:

  dakar_nginx:
      container_name: dakar_nginx
      build:
        context: ../app
        dockerfile: Dockerfile
      depends_on:
        - dakar_backend
      tty: false
      ports:
        - 80:80
      volumes:
        - ../app:/app
      networks:
        - dgraph_default

  dakar_backend:
      container_name: dakar_backend
      build:
        context: ../backend
        dockerfile: Dockerfile
      depends_on:
        - zero
        - ratel
        - dashd
        - alpha
      tty: false
      restart: unless-stopped
      ports:
        - 8081:8081
      expose:
        - 8081
      networks:
        - dgraph_default