nodeLinker: node-modules

npmScopes:
  blockchain:
    npmAlwaysAuth: true
    npmRegistryServer: "https://git.gvk.idi.ntnu.no/api/v4/projects/410/packages/npm/"
  blockchain-privacy:
    npmAlwaysAuth: false
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
