allowBuilds:
  '@parcel/watcher': false
  unrs-resolver: false
minimumReleaseAge: 10080 # defaults to 1 day, increase to 7 days (in minutes)
minimumReleaseAgeExclude: # internal packages
  - '@blockchain-privacy/*'
  - '@blockchain/*'
