// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	chainhash "github.com/btcsuite/btcd/chaincfg/chainhash"

	mock "github.com/stretchr/testify/mock"

	rpcclient "github.com/btcsuite/btcd/rpcclient"
)

// BatchRPCClient is an autogenerated mock type for the BatchRPCClient type
type BatchRPCClient struct {
	mock.Mock
}

// GetBlockCountAsync provides a mock function with given fields:
func (_m *BatchRPCClient) GetBlockCountAsync() rpcclient.FutureGetBlockCountResult {
	ret := _m.Called()

	var r0 rpcclient.FutureGetBlockCountResult
	if rf, ok := ret.Get(0).(func() rpcclient.FutureGetBlockCountResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rpcclient.FutureGetBlockCountResult)
		}
	}

	return r0
}

// GetRawTransactionVerboseAsync provides a mock function with given fields: txHash
func (_m *BatchRPCClient) GetRawTransactionVerboseAsync(txHash *chainhash.Hash) rpcclient.FutureGetRawTransactionVerboseResult {
	ret := _m.Called(txHash)

	var r0 rpcclient.FutureGetRawTransactionVerboseResult
	if rf, ok := ret.Get(0).(func(*chainhash.Hash) rpcclient.FutureGetRawTransactionVerboseResult); ok {
		r0 = rf(txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rpcclient.FutureGetRawTransactionVerboseResult)
		}
	}

	return r0
}

// Send provides a mock function with given fields:
func (_m *BatchRPCClient) Send() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
