// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	blockiterator "backend/blockiterator"
	context "context"

	external "backend/external"

	log "log"

	mock "github.com/stretchr/testify/mock"
)

// BlockIterator is an autogenerated mock type for the BlockIterator type
type BlockIterator struct {
	mock.Mock
}

// CalculateInitialState provides a mock function with given fields:
func (_m *BlockIterator) CalculateInitialState() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Context provides a mock function with given fields:
func (_m *BlockIterator) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// Db provides a mock function with given fields:
func (_m *BlockIterator) Db() external.Database {
	ret := _m.Called()

	var r0 external.Database
	if rf, ok := ret.Get(0).(func() external.Database); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(external.Database)
		}
	}

	return r0
}

// Empty provides a mock function with given fields:
func (_m *BlockIterator) Empty() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetHighestAvailableBlock provides a mock function with given fields:
func (_m *BlockIterator) GetHighestAvailableBlock() (uint64, error) {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementState provides a mock function with given fields:
func (_m *BlockIterator) IncrementState() {
	_m.Called()
}

// Iterate provides a mock function with given fields:
func (_m *BlockIterator) Iterate() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logger provides a mock function with given fields:
func (_m *BlockIterator) Logger() *log.Logger {
	ret := _m.Called()

	var r0 *log.Logger
	if rf, ok := ret.Get(0).(func() *log.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*log.Logger)
		}
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *BlockIterator) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PostExecution provides a mock function with given fields:
func (_m *BlockIterator) PostExecution() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetState provides a mock function with given fields: _a0
func (_m *BlockIterator) SetState(_a0 blockiterator.State) {
	_m.Called(_a0)
}

// State provides a mock function with given fields:
func (_m *BlockIterator) State() blockiterator.State {
	ret := _m.Called()

	var r0 blockiterator.State
	if rf, ok := ret.Get(0).(func() blockiterator.State); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(blockiterator.State)
	}

	return r0
}
