// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/dgraph-io/dgo/v210/protos/api"

	dgo "github.com/dgraph-io/dgo/v210"

	mock "github.com/stretchr/testify/mock"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// Alter provides a mock function with given fields: ctx, op
func (_m *Database) Alter(ctx context.Context, op *api.Operation) error {
	ret := _m.Called(ctx, op)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.Operation) error); ok {
		r0 = rf(ctx, op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mutate provides a mock function with given fields: ctx, req
func (_m *Database) Mutate(ctx context.Context, req *api.Request) (*api.Response, error) {
	ret := _m.Called(ctx, req)

	var r0 *api.Response
	if rf, ok := ret.Get(0).(func(context.Context, *api.Request) *api.Response); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *api.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTxn provides a mock function with given fields:
func (_m *Database) NewTxn() *dgo.Txn {
	ret := _m.Called()

	var r0 *dgo.Txn
	if rf, ok := ret.Get(0).(func() *dgo.Txn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dgo.Txn)
		}
	}

	return r0
}

// Query provides a mock function with given fields: ctx, q, vars
func (_m *Database) Query(ctx context.Context, q string, vars map[string]string) (*api.Response, error) {
	ret := _m.Called(ctx, q, vars)

	var r0 *api.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) *api.Response); ok {
		r0 = rf(ctx, q, vars)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, q, vars)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
