// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	btcjson "github.com/btcsuite/btcd/btcjson"
	chainhash "github.com/btcsuite/btcd/chaincfg/chainhash"

	mock "github.com/stretchr/testify/mock"

	rpcclient "github.com/btcsuite/btcd/rpcclient"
)

// RPCClient is an autogenerated mock type for the RPCClient type
type RPCClient struct {
	mock.Mock
}

// GetBlockChainInfo provides a mock function with given fields:
func (_m *RPCClient) GetBlockChainInfo() (*btcjson.GetBlockChainInfoResult, error) {
	ret := _m.Called()

	var r0 *btcjson.GetBlockChainInfoResult
	if rf, ok := ret.Get(0).(func() *btcjson.GetBlockChainInfoResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*btcjson.GetBlockChainInfoResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockChainInfoAsync provides a mock function with given fields:
func (_m *RPCClient) GetBlockChainInfoAsync() rpcclient.FutureGetBlockChainInfoResult {
	ret := _m.Called()

	var r0 rpcclient.FutureGetBlockChainInfoResult
	if rf, ok := ret.Get(0).(func() rpcclient.FutureGetBlockChainInfoResult); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(rpcclient.FutureGetBlockChainInfoResult)
	}

	return r0
}

// GetBlockCount provides a mock function with given fields:
func (_m *RPCClient) GetBlockCount() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockHash provides a mock function with given fields: blockHeight
func (_m *RPCClient) GetBlockHash(blockHeight int64) (*chainhash.Hash, error) {
	ret := _m.Called(blockHeight)

	var r0 *chainhash.Hash
	if rf, ok := ret.Get(0).(func(int64) *chainhash.Hash); ok {
		r0 = rf(blockHeight)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chainhash.Hash)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(blockHeight)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockVerbose provides a mock function with given fields: blockHash
func (_m *RPCClient) GetBlockVerbose(blockHash *chainhash.Hash) (*btcjson.GetBlockVerboseResult, error) {
	ret := _m.Called(blockHash)

	var r0 *btcjson.GetBlockVerboseResult
	if rf, ok := ret.Get(0).(func(*chainhash.Hash) *btcjson.GetBlockVerboseResult); ok {
		r0 = rf(blockHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*btcjson.GetBlockVerboseResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*chainhash.Hash) error); ok {
		r1 = rf(blockHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRawTransactionVerbose provides a mock function with given fields: txHash
func (_m *RPCClient) GetRawTransactionVerbose(txHash *chainhash.Hash) (*btcjson.TxRawResult, error) {
	ret := _m.Called(txHash)

	var r0 *btcjson.TxRawResult
	if rf, ok := ret.Get(0).(func(*chainhash.Hash) *btcjson.TxRawResult); ok {
		r0 = rf(txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*btcjson.TxRawResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*chainhash.Hash) error); ok {
		r1 = rf(txHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
