# This Docker Compose file can be used to quickly bootup Dgraph Zero
# and Alpha in different Docker containers.

# It mounts /tmp/data on the host machine to /dgraph within the
# container. You can change /tmp/data to a more appropriate location.
# Run `docker-compose up` to start Dgraph.

version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
    networks:
        - dgraph_default
  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --lru_mb=2048 --zero=zero:5080 --whitelist 172.17.0.0:172.25.0.0,192.168.188.0:192.168.188.255
    networks:
        - dgraph_default
  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
    networks:
        - dgraph_default
  dash:
    image: dashpay/dashd:latest
    volumes:
      - /tmp/dash:/dash
    ports:
      - 9999:9999
      - 9998:9998
    restart: on-failure
    networks:
      - dash_default

networks:
  dgraph_default:
    external: true
  dash_default:
    external: true