- id: "ory:wikiapi_protected"
  upstream:
    preserve_host: true
    url: "http://wikiapi:4567"
    strip_path: "/wiki"
  match:
    url: "http://localhost:4455/wiki/<.*>"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: json
      config:
        verbose: false
- id: "ory:kratosadmin_admin"
  upstream:
    preserve_host: true
    url: "http://host.docker.internal:9316"
    strip_path: "/kratosadmin"
  match:
    url: "http://localhost:4455/kratosadmin/<(?!self).*>"
    methods:
      - GET
      - POST
      - DELETE
      - PUT
      - HEAD
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: remote_json
    config:
      remote: http://keto:4466/relation-tuples/check
      payload: |
        {
          "subject_id": "{{ index .Extra.identity.metadata_public.roles 0 | print }}",
          "relation": "call",
          "namespace": "Service",
          "object": "kratosadmin_admin"
        }
  mutators:
    - handler: header
  errors:
    - handler: json
      config:
        verbose: false
- id: "ory:kratosadmin_protected"
  upstream:
    preserve_host: true
    url: "http://host.docker.internal:9316"
    strip_path: "/kratosadmin"
  match:
    url: "http://localhost:4455/kratosadmin/self/<.*>"
    methods:
      - GET
      - POST
      - DELETE
      - PUT
      - HEAD
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: remote_json
    config:
      remote: http://keto:4466/relation-tuples/check
      payload: |
        {
          "subject_id": "{{ index .Extra.identity.metadata_public.roles 0 | print }}",
          "relation": "call",
          "namespace": "Service",
          "object": "kratosadmin_protected"
        }
  mutators:
    - handler: header
  errors:
    - handler: json
      config:
        verbose: false
- id: "ory:dakar_public"
  upstream:
    preserve_host: true
    url: "http://host.docker.internal:8081"
  match:
    url: "http://localhost:4455/api/v1/blockchain/<.*>"
    methods:
      - GET
      - POST
      - DELETE
      - PUT
      - HEAD
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: json
      config:
        verbose: true
- id: "ory:dakar_protected"
  upstream:
    preserve_host: true
    url: "http://host.docker.internal:8081"
  match:
    url: "http://localhost:4455/api/v1/<(?!blockchain).*>"
    methods:
      - GET
      - POST
      - DELETE
      - PUT
      - HEAD
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: remote_json
    config:
      remote: http://keto:4466/relation-tuples/check
      payload: |
        {
          "subject_id": "{{ index .Extra.identity.metadata_public.roles 0 | print }}",
          "relation": "call",
          "namespace": "Service",
          "object": "dakar_protected"
        }
  mutators:
    - handler: header
  errors:
    - handler: json
      config:
        verbose: false
